export interface User {
    name: string,
    last_name: string,
    email: string,
    password: string,
    profile_picture: string,
    type: 'regular',
    status: "active" | "inactive" | "blocked",
    phone: string,
    accepted_terms_conditions: boolean,
    address: string,
    favorites?: any,
    seller: string,
    pending_purchase: number,
    canceled_purchase: number,
    success_purchase: number,
    deleted: Date,
    createdAt: Date,
    lastUpdated: Date,
    _id?: string,
}
